name: Integration Tests On Neo4j Aura

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CONNECTIONS: ${{ secrets.AURA_CONNECTIONS }}
    name: "Running Integration tests for PHP ${{ matrix.php-version }} on a Neo4j Aura Instance"
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.0", "8.2"]

    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: ${{ matrix.php-version }}
          version: 2
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          memory_limit: 1024M
          version: 9
          testsuite: Integration
          bootstrap: vendor/autoload.php
