name: Integration Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CONNECTIONS: $AURA_CONNECTIONS
    name: "Running Integration tests for PHP ${{ matrix.php-version }} on a Neo4j Aura Instance"
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.0", "8.2"]

    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: ${{ matrix.php-version }}
          version: 2
      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite Integration
